---
- name: deploy Argocd
  hosts: all
  become: yes
  # vars:
  #     ansible_python_interpreter: /usr/bin/python3
  # collections:
  #   - community.kubernetes
  roles:
    - namespace
    - secret
    - argocd