---
- name: copy file to remote
  copy:
    src: secret.yml
    dest: /tmp/secret.yml
  register: copy_file_secret

# - name: debug
#   debug:
#     msg: "{{ copy_file_secret }}"

- name: Apply secret.yml
  shell: kubectl apply -f /tmp/secret.yml
  when: copy_file_secret.changed