apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  namespace: argocd  # Thay đổi nếu cần
type: Opaque
data:
  username: eW91cl91c2VybmFtZQ==  # Mã hóa Base64 của 'your_username'
  password: eW91cl9wYXNzd29yZA==  # Mã hóa Base64 của 'your_password'